title: BaseEngine文档
description: 快速使用DataBinding + ViewModel实现MVVM进行开发，自动加载缺省页、Dialog、Toast。
theme: just-the-docs

url: https://Chen-Xi-g.github.io

aux_links:
  Template Repository: https://github.com/Chen-Xi-g/Chen-Xi-g.github.io
