# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 一个用Github搭建的个人Blog
description: 这个Blog用来展示个人的Api文档和随手笔记。
baseurl: # the subpath of your site, e.g. /support
url: https://chen-xi-g.github.io/ # the base hostname AND PROTOCOL for your site, e.g. http://example.com
permalink: /:categories/:title

content_type: 忞鹿 Blog #Define whether this is a knowledge base, help center, or something else
use_authors: true #Set this to false to disable showing post authors

brand_logo: https://blog.minlukj.com/wp-content/uploads/2020/08/组-27144.png
brand_name: 忞鹿
header: 感谢你的到来，我将在这里分享知识?
subheader: 这里仅用来展示API文档和随手笔记

meta_image: odin-meta.png

# Social Links
twitter_username: 忞鹿
facebook_page:
github_username: ChenXi
email: a912816369@gmail.com
linkedin_page:
instagram_username: 


# Navivation
nav_item_one: Github
nav_item_one_link: https://github.com/TeaGuns/odin

nav_item_two: Blog
nav_item_two_link: http://me.minlukj.com/

nav_item_three: #
nav_item_three_link: #

nav_button: 返回到主页
nav_button_link: https://chen-xi-g.github.io/

# More Help
help_one_title: 忞鹿代码库
help_one_content: 这里有本人所有的开源代码仓库，可以帮助更高效的开发，欢迎Start.
help_one_button: Github
help_one_link: https://github.com/TeaGuns/odin/issues

help_two_title: Twitter
help_two_content: Feel free to tweet at me if you have suggestions for Odin. Or if you just want to say hi.
help_two_button: Twitter
help_two_link: https://github.com/Chen-Xi-g

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
